### ISSUE TITLE
Frame: 1 -> Advance: 0

### ISSUE THREAD

**Issue by Liger0** [Admiral-Fish/PokeFinder#108]
It would be useful to be able to use an initial frame of 0.
This way, once the delay is set up correctly, you can verify for tests purposes that you are on the correct frame, as the correct spread will appear at the first frame.

**Comment by Admiral-Fish** [comment]
I don't see how this would be useful. Frame 1 has been used for the longest time and would probably only cause confusion to everyone that is used to frame 1.

**Comment by Liger0** [comment]
Because, if you want to know at which seed to stop, you can input it and see if at 0 you have the result you want instead of using LCRNG (R). 
That is what I've always done with the rng reporter. 
Even if it is not used by default, can't it be a valid input?

**Comment by ozderya** [comment]
Wen you RNG Ageto Celebi and Colosseum Pikachu, Frame 0 will be useful to fallow/verify your current seed. Not really sure if it is useful for another RNG, but I definitely wanted to see frame of 0 when I was RNGing them.

**Comment by zaksabeast** [comment]
Alongside discussing whether the initial frame should be 0 or 1, I think a relevant topic that could influence this discussion is whether the word 'frame' should be changed to 'advance'.

Gens 1-4 advances the RNG with the vblank, so video frames are used to track the advancement of RNG.  That is, 1 frame is 1 RNG advancement.  When RNG for Gens 5-7 came out, they kept the terminology, but some Gen 5 RNGs and all Gen 6/7 RNGs don't advance based on frames - the term is used incorrectly there.

Since 1 frame represents 1 RNG advancement, it makes sense to refer to 'frames' as 'advances' when talking across multiple generations (or all generations for consistency).

I don't believe renaming 'frame' to 'advance' would be confusing to people either; quite the opposite, this would be better for the user experience.  Someone new to RNG might have trouble understanding what a 'frame' is, and will more easily understand what an 'RNG advance' is.  Someone who has done RNG for a long time will know what an 'RNG advance' is too.  Starting with Gen 8, some tools started moving to the term 'advance' as well, so any new RNGers due to Gen 8 will already know the term.

Tying this back to the original discussion, if 1 frame represents 1 advance, and the current Pokemon generated by the game is in 0 advances (because we don't advance the RNG to get the current Pokemon), the same frame would be represented as 'frame 0'.

@Admiral-Fish What are thoughts on moving from `Frame: 1` -> `Advance: 0` given that:
- 'advance' is a more accurate term
- 'advance' can be more easily understood by both new and old users
- The game starts with 0 RNG advances when it's initialized, so it would satisfy the 'start with 0' request

**Comment by Admiral-Fish** [comment]
Switching the terminology to advances as well seems better. Advance: 0 sounds much better then Frame: 0 and I wouldn't be opposed to changing it.
