### ISSUE TITLE
Unable to locat profiles

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#166]
This window appears every time i open the app (last commit), even if i set in settings the path in which i have the profile file.

![image](https://user-images.githubusercontent.com/20956021/124370860-10275280-dc7c-11eb-8ada-a5b6096f0cbd.png)

I tryed opening old Pokefinder versions and i don't get the error. Profiles are anyway loaded correctly in last commit.

**Comment by Admiral-Fish** [comment]
Older versions don't have this since I recently added it (see #157). That should only trigger if the existing profile path in settings can't be located. Are you able to debug to see what is going wrong on your end? It worked correctly for me when I was testing it.

Does it display the correct profiles even after showing that messagebox?

**Comment by Real96** [comment]
> Older versions don't have this since I recently added it (see #157). That should only trigger if the existing profile path in settings can't be located. Are you able to debug to see what is going wrong on your end? It worked correctly for me when I was testing it.
> 
> Does it display the correct profiles even after showing that messagebox?

I tryed debugging but there is a problem: this happens only if you set Release on Qt. If you set Debug the error won't arrive. Also yes, profiles are loaded correctly even if there is this error

**Comment by Admiral-Fish** [comment]
Try again with 1268e06

**Comment by Real96** [comment]
> Try again with [1268e06](https://github.com/Admiral-Fish/PokeFinder/commit/1268e06d0b8509edc202ca6d4eeeef84f8b15ce4)

Fixed!
