### ISSUE TITLE
Add missing leads

### ISSUE THREAD

**Issue by Admiral-Fish** [Admiral-Fish/PokeFinder#184]
Static
Magnet pull
Pressure (and friends)
Compound eyes (and friends)

Maybe level ones, probably not
pls help

**Comment by RichardPaulAstley** [comment]
Everything is important tbh. Levels can give better solution for some specific case. 

These are the main ones for the levels : 

Hustle / Vital Spirit / Pressure : 50% (on the generation) to find a Pokémon with a higher level than your lead
Intimidate / Keen Eye  : 50% (on the generation) to avoid a Pokémon with a lower level than your lead.

I avoid the ones that implies Sweet Scentless stuff (tell me if you're interested) 

These are a thing since Emerald but I'd double check on that.

**Comment by ShinySylveon04** [comment]
More info for Compound Eyes:

- Normal rates: 45 / 95
- Compound Eyes: 20 / 80

**Comment by Admiral-Fish** [comment]
Closing as fixed via redesign branch. Gen 5 will have the appropriate leads added when implemented
