### ISSUE TITLE
Gen 5 TID - Unable to Locate ID Hit

### ISSUE THREAD

**Issue by papajefe** [Admiral-Fish/PokeFinder#312]
Opted to give new Pokefinder a try for Gen 5.

Profile setup went smoothly, but ran into an issue with TID\SID.

Tried on 4.10 as well as the latest Nightly on Appveyor as of today. Was unable to find this ID 04235.

RNG Reporter had no issue, despite double checking Profile info and making sure it all matched. Even tried making a brand new profile with the same info, in case MAC address got borked when I switched to the Nightly. No dice.

![Capture](https://github.com/Admiral-Fish/PokeFinder/assets/16225603/24f1d53a-e530-45f0-bde1-3ce880ca362b)

**Comment by SteveCookTU** [comment]
This is hard to recreate since parameters are fairly unique for all users with profile data. 

I was able to determine the source of the difference is the number of initial advances. PokeFinder calculates 27 as the initial advances while reporter says 17. Since it's on frame 18 PokeFinder searches past it. 

Is this a confirmed TID you received in-game? If so my guess is PokeFinder contains the error and not RNG Reporter.

**Comment by Admiral-Fish** [comment]
It's not possible to hit that frame. I RAM hacked that seed and hit 27 for my initial advances.

**Comment by papajefe** [comment]
> It's not possible to hit that frame. I RAM hacked that seed and hit 27 for my initial advances.
> 
> FC376D8B36C35B1D 27 28 47820 18971 7706 2022-12-25 13:05:30

I literally did hit the seed in game... but here's the thing: I forgot to wipe my save data.

So apparently, when you still have an existing save file, it changes the initial frame.

**Comment by Admiral-Fish** [comment]
Yeah having an existing save file changes things. I just make the assumption you are starting without a save file existing.
