### ISSUE TITLE
[Gen 4] Suggestion to remove the "Delay" box from the generator tab in gen 4

### ISSUE THREAD

**Issue by cervizzz** [Admiral-Fish/PokeFinder#354]
At least from the breeding and wild sections, it doesn't have any use other than confusing people that put their seed's delay there not knowing it will cause X amount of advances to be skipped.

I understand it can be used for stuff that is generated a few advances down the road like some starters and DPPt roamers, but now that Pokefinder differentiates by encounter, these "delays" or "starting frames" could be pre-selected so you always need to stop on the advance before your target without needing the delay box.

**Comment by SteveCookTU** [comment]
Delay in this context has always been defined as the uncontrolled advances that happen between the last input and when the generation of the Pokemon starts. This can be variable from user to user and is unlikely to change on the GUI.

**Comment by cervizzz** [comment]
In its current implementation "Delay" skips X amount of states starting from the first one. Which is fine for gen 3 where manipulating is a timing issue, but not for gens 4 and 5 where you manually advance through each state and actually need that information.

As an example, let's say I'm going for Mesprit, a roamer in Platinum that is generated 5 advances past the current state instead of the usual 1, so I put 5 in the delay box. Now the tool has skipped the first 5 states and I can't see the Chatot pattern that I need to follow.

Hope this pics can better explain what I'm trying to say, I made the target shiny so its easier to track.

With 0 delay I'd stop at the selected state to get my target:
![delay0](https://github.com/Admiral-Fish/PokeFinder/assets/84414039/ec932462-fc70-41c3-801a-fa509fdf6945)


With 5 delay, now the Chatot cries and/or calls are gone. Even if the amount of advances is right, counting instead of following along the pattern is bad practice and prone to error, specially for higher targets.
![delay5](https://github.com/Admiral-Fish/PokeFinder/assets/84414039/281f9119-6683-4bf1-ad5b-764018c4b578)


I'd love for the behavior of the delay to only shift the values of the Pokemon, which can be inferred from the encounter itself, thus not needing a delay box anymore. Something like this:
![delay5 new](https://github.com/Admiral-Fish/PokeFinder/assets/84414039/852426a4-f468-4d02-87c9-e9bd863f1384)

I don't think this is "variable from user to user" and is encounter based instead. I also believe calling it "delay" in gen 4 is an issue in and of itself when we use the same word to refer to a part of the initial seed and works as a filter with a completely different function in the searcher tab. I've seen many beginners being confused after putting the delay from their target seed in the generator.

**Comment by SteveCookTU** [comment]
Going based on the encounter and forcing that delay behind the scenes would cause the same issue you mention with the missing Chatot pitches. Also shifting only half of the data would cause a lot confusion to majority of users than having the delay box for beginners. The alignment says at this advancement from the start of the game, this is what the game produces. 

Seeing as this is more specific to gen 4, it really seems more like a naming issue for Gen 4 or a terminology issue for guides that beginners are using. Not trying to be ignorant to beginners, but the common practice which should be taught is having a delay of 0 and then changing that to match what advancement was actually reached in-game. If I aim for 15 and hit 205, I re-calibrate by setting the delay to 5. Then the tool will show a more accurate result on the advance I am aiming for.

For example, a guide would mention the process of doing the initial seed and then note a different number for the delay for the generator tab. A Mesprit guide may deliberately say to set it to 5 or to change the delay based on where the user landed.

Keeping a pattern throughout all generations is the key here for the basic level of usage so not having it available for one generation but not another would still cause confusion in the other direction (more advanced users). That's why it is variable from user to user.

**Comment by cervizzz** [comment]
I understand where you are coming from, I just don't think the current implementation helps deal with these unavoidable advances. Advanced users simply know that they need to stop X advances (it is always the same for that encounter) before for certain encounters, because there is just 4 of them.

> the common practice which should be taught is having a delay of 0 and then changing that to match what advancement was actually reached in-game. If I aim for 15 and hit 205, I re-calibrate by setting the delay to 5. Then the tool will show a more accurate result on the advance I am aiming for.

You'd be in a worse spot if you did that. Adding a delay to pokefinder won't change that you still need to stop 5 advances before your target, and now you would be missing important information from the advances that were skipped, and the Chatot cries /call results that you get in game would not match what pokefinder shows (as in, the first Chatot cry in game will be different than the first Chatot cry shown in pokefinder).

> Keeping a pattern throughout all generations is the key here for the basic level of usage so not having it available for one generation but not another would still cause confusion in the other direction (more advanced users). That's why it is variable from user to user.

I completely understand the value of cohesiveness, but this is more about removing unnecessary clutter from the UI. It makes sense to keep the "Lead" option for gens 4 and 5 static encounters but not for gen 3, and in the same vein the delay option that can be useful for gen 3 doesn't add any value to gens 4 and 5.

> Going based on the encounter and forcing that delay behind the scenes would cause the same issue you mention with the missing Chatot pitches. Also shifting only half of the data would cause a lot confusion to majority of users than having the delay box for beginners. 

Of course, it was just a suggestion. I'd be down to just remove it, making it into a toggle with the correct preset value, or a hover info window warning users that this particular encounter has a delay between the last input and the generation.
