### ISSUE TITLE
Does not generate valid PID for Pokémon Colosseum

### ISSUE THREAD

**Issue by extherian** [Admiral-Fish/PokeFinder#358]
Even with a valid initial seed taken from a running copy of Pokémon Colosseum, PKHeX will always report any PID/IV/Nature spread generated by this tool as invalid. By contrast, any PID/IV/Nature spread generated by Eligor will always be detected as valid. Please change the method used to match the one used by Eligor.

**Comment by Admiral-Fish** [comment]
All of my implementations have been tested and verified in game as correct.

I do not support or condone hacking and any use case of hacking will not be supported.

**Comment by DustinOgan** [comment]
I think this is a valid issue.  Let me give some steps to reproduce and you can make your own decision on it:

1. Begin a new game of Pokemon Colosseum on Wii utilizing the built in Gamecube
2. Play up to the first save in Phenac Town and rescue your companion
3. Save the game at the PC
4. Utilize GCMM to extra the save to an SDCard so that you can see the IV spread of you legitimate pokemon in PKHex
5. Utilize method Gen3Tools > GamecubeSeedFinder 
6. Click the Colo tab
7. Follow the prescribed method of Noting Trainer / Lead , up to 7 times to generate the init seed.
8. Utlize PokeFinder with the seed from step 7, and the TID and SID of the pokemon from step 4
9. Narrow the IV , nature and hidden ability to be exactly your legitimate Pokemon.

Result:  The pokemon will not be found by the tool 

By comparison 
1. Enable TSID matching in Eligor
2. Put your TID and SID from step 4
3. Paste your seed in Initial Seed (Hex)
4. Narrow the IVs and nature and hidden ability to exactly your legitimate Pokemon.

Result: Eligor will return a match for your TID/SID exactly for precisely your legitimate Pokemon's PID.
