### ISSUE TITLE
make it work without installing appveyor and mess

### ISSUE THREAD

**Issue by Orionsilver** [Admiral-Fish/PokeFinder#36]
# **PLZ**
![mkkkd](https://user-images.githubusercontent.com/18640392/34984311-ebfa192a-fac9-11e7-8f88-a14f2663d629.jpg)

**Comment by Admiral-Fish** [comment]
Not entirely sure what you mean by this. You are able to download the latest commit from appveyor by clicking on either the 32bit build or 64bit build then going to artifacts and downloading either the .7z or .zip file. Alternatively you can wait for a new release or compile the project yourself.

As for Egg and ID those haven't been added yet.

**Comment by Orionsilver** [comment]
@Admiral-Fish i do not have appveyor and mess in my Laptop 
and i try to click on them i see blank 
![image](https://user-images.githubusercontent.com/18640392/35002912-a0a74a7a-fb04-11e7-86ca-1b4191349a45.png)
![image](https://user-images.githubusercontent.com/18640392/35002920-a89045b6-fb04-11e7-9399-01f0ad7ab50a.png)
![image](https://user-images.githubusercontent.com/18640392/35002935-afb6a2e0-fb04-11e7-9e73-0bc1e4a3e279.png)
![image](https://user-images.githubusercontent.com/18640392/35002941-b4d1f5ea-fb04-11e7-9053-dac416f0c0ab.png)

and i redownload it and still see it blank

**Comment by Admiral-Fish** [comment]
Is that from the github release?

I don't think it is possible to install appveyor on a computer since it is just a cloud service.

You can try the latest commit from appveyor here for 64 bit https://ci.appveyor.com/project/Admiral-Fish/pokefinder/build/job/cg7eiptum2nao55d/artifacts

And 32 bit https://ci.appveyor.com/project/Admiral-Fish/pokefinder/build/job/eawy6o33kdh28w99/artifacts

Just click either 7z or zip file to download it.

**Comment by Orionsilver** [comment]
THX U SO MUCH 👍
