### ISSUE TITLE
[Gen 3] RSE (ONLY) Safari Zone Fishing and maybe Rock Smash

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/PokeFinder#65]
![image](https://user-images.githubusercontent.com/25870563/52600494-1c68a600-2e5c-11e9-8a40-c3d8396f9e84.png)
^the screen of the issue i've stated in the discord

**Comment by Admiral-Fish** [comment]
Dumping this link for later reference
https://github.com/pret/pokeruby/blob/master/src/wild_encounter.c#L3951

**Comment by RichardPaulAstley** [comment]
I'm gonna ad the Rock Smash issue i'm getting in the Safari Zone.
It could mess up like it does for Fishing, no way to get something working there.

As reminder, in RSE, the wild function is different in the Safari Zone, and so should be applied to every case (Fishing, Rock Smash)

Making some of them broken

**Comment by Real96** [comment]
Rock Smash Fix
Rock smash has to be fixed in both RS ane E, inside and outside the Safari Zone.
To get correct rock smash spreads i used researcher + safari zone encounter type. The battle triggering prng is at frame 45725, the spread+pid are generated from the next prng, so 45726. The PID/spread i got matches perfectly Safari encounter type research as you can see in this screen (PID/spread are at frame 45726).

![1](https://user-images.githubusercontent.com/20956021/80203765-fa55e080-8627-11ea-8182-5c1bca4419fa.png)

Comparing rock smash encounter type results to it, frame is wrong (should be +1, as you can see the pid is the same of safari encounter type research but frame is -1) and it generates the spread from the wrong prng seed. Atm it is using the prng which trigger the battle but instead it should use the next one.

![2](https://user-images.githubusercontent.com/20956021/80204358-00988c80-8629-11ea-831e-650f90be156a.png)

This happens also outside safari zone, you can apply the same thing comparing grass / rock smash.

**Comment by Real96** [comment]
Fishing fix
Fishing has to be fixed for both RS and E inside Safari zone only (it is ok outside).
PID and spread are ok, the only problem is that level and encounter slots are in the previous frame as you can see in this screen:

![3](https://user-images.githubusercontent.com/20956021/80207240-19577100-862e-11ea-8331-f2ce42e8d327.png)

This happens with all 3 rods

**Comment by RichardPaulAstley** [comment]
You can add fishing to the list

**Comment by Real96** [comment]
Fixed in #127
